### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by athaax** [gistia/json-log-viewer#1]
Hey there!

Tried giving your json log viewer a spin but I couldn't get it going. 

some specs:
windows 10 x64
using git bash
node v8.7.0

```
$ jv logs/dev.log
TypeError: Cannot read property 'length' of undefined
    at len (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\utils.js:42:17)
    at padEnd (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\utils.js:50:28)
    at columns.map.column (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\utils.js:13:14)
    at Array.map (<anonymous>)
    at rows.map.row (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\utils.js:8:20)
    at Array.map (<anonymous>)
    at formatRows (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\utils.js:7:15)
    at MainPanel.update (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\widgets\MainPanel.js:440:21)
    at MainPanel.renderLines (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\widgets\MainPanel.js:92:10)
    at MainPanel.loadFile (C:\Users\JonathanCS\AppData\Local\Yarn\config\global\node_modules\json-log-viewer\src\widgets\MainPanel.js:39:10)
```

**Comment by fcoury** [comment]
Hey @athaax I am not sure why but I don't receive GitHub notification when a new Issue is raised.

Do you mind posting your log file here?

**Comment by dgladbach** [comment]
Hey!
Same problem here.
Linux Mint 18.2
node v9.2.0

```
$jv censored.log
TypeError: Cannot read property 'length' of undefined
    at len (/usr/local/lib/node_modules/json-log-viewer/src/utils.js:42:17)
    at padEnd (/usr/local/lib/node_modules/json-log-viewer/src/utils.js:50:28)
    at columns.map.column (/usr/local/lib/node_modules/json-log-viewer/src/utils.js:13:14)
    at Array.map (<anonymous>)
    at rows.map.row (/usr/local/lib/node_modules/json-log-viewer/src/utils.js:8:20)
    at Array.map (<anonymous>)
    at formatRows (/usr/local/lib/node_modules/json-log-viewer/src/utils.js:7:15)
    at MainPanel.update (/usr/local/lib/node_modules/json-log-viewer/src/widgets/MainPanel.js:440:21)
    at MainPanel.renderLines (/usr/local/lib/node_modules/json-log-viewer/src/widgets/MainPanel.js:92:10)
    at MainPanel.loadFile (/usr/local/lib/node_modules/json-log-viewer/src/widgets/MainPanel.js:39:10)
```
My logfile is generated by [Monolog](https://github.com/Seldaek/monolog) and looks like this
```
{"message":"Matched route \"**_heartbeat_check\" (parameters: \"_controller\": \"**\\Controller\\**Controller::heartbeatCheckAction\", \"_route\": \"**_heartbeat_check\")","context":[],"level":200,"level_name":"INFO","channel":"request","datetime":{"date":"2017-12-06 09:23:42.253060","timezone_type":3,"timezone":"Europe/Berlin"},"extra":[]}
{"message":"Fatal Error: Call to a member function forceLogout() on null","context":{"type":1,"file":"/var/www/html/***BO.php","line":75,"level":-1,"stack":[{"function":"getAutoLogoutInfo","type":"->","class":"**\\BusinessObjects\\**BO","file":"/var/www/html/**Controller.php","line":28,"args":[]},{"function":"heartbeatCheckAction","type":"->","class":"**\\Controller\\**Controller","file":"/var/www/html/**/app/bootstrap.php.cache","line":3054,"args":[]}]},"level":600,"level_name":"EMERGENCY","channel":"php","datetime"{"date":"2017-12-06 09:23:42.434108","timezone_type":3,"timezone":"Europe/Berlin"},"extra":[]}
```

**Comment by fcoury** [comment]
Thanks @dgladbach I'll work on it and let you know!

**Comment by fcoury** [comment]
@dgladbach this should fix your issue. 

Please also note that the second line on the log file you provided on your example isn't valid JSON:

[JSON Linter Link](https://jsonlint.com/?json={%22message%22:%22Fatal%20Error:%20Call%20to%20a%20member%20function%20forceLogout()%20on%20null%22,%22context%22:{%22type%22:1,%22file%22:%22/var/www/html/***BO.php%22,%22line%22:75,%22level%22:-1,%22stack%22:[{%22function%22:%22getAutoLogoutInfo%22,%22type%22:%22-%3E%22,%22class%22:%22**\\BusinessObjects\\**BO%22,%22file%22:%22/var/www/html/**Controller.php%22,%22line%22:28,%22args%22:[]},{%22function%22:%22heartbeatCheckAction%22,%22type%22:%22-%3E%22,%22class%22:%22**\\Controller\\**Controller%22,%22file%22:%22/var/www/html/**/app/bootstrap.php.cache%22,%22line%22:3054,%22args%22:[]}]},%22level%22:600,%22level_name%22:%22EMERGENCY%22,%22channel%22:%22php%22,%22datetime%22{%22date%22:%222017-12-06%2009:23:42.434108%22,%22timezone_type%22:3,%22timezone%22:%22Europe/Berlin%22},%22extra%22:[]})

![image](https://user-images.githubusercontent.com/1371/33682325-405d2c50-daae-11e7-8186-333870dc8fd6.png)
